[package]
name = "mentos"
version = "0.1.0"
authors = ["Shella Stephens <pirateshella@gmail.com>"]
edition = "2018"

[dependencies]
bufstream = "0.1"
env_logger = "0.5"
failure = "0.1"
quick-xml = "0.12"
serde = "1.0"
serde_derive = "1.0"
ssh2 = "0.3"
structopt = "0.2"
toml = "0.4"
